// CommentBot — content script（支援 YouTube 與 Facebook）
// 聚焦式（focus-driven）單則留言回覆：當使用者點開某則留言的回覆框（該框取得焦點）時，
// 只針對「那一則」留言，透過 background 用選定的 AI 產生一則回覆並填入回覆框，
// 由使用者確認後手動送出。一次只處理當下 focus 的一則，避免大量產生而消耗過多 token。
// 平台差異（選擇器、擷取留言、填入方式）集中在 PLATFORMS，其餘邏輯共用。

'use strict';

const BTN_LABEL = '✨ AI 產生回覆';

let cachedSettings = normalizeSettings(null);
let generating = false;
const autoGenerated = new Set(); // 本頁工作階段中已「自動」產生過的留言 key
let lastHref = location.href;

// 目前選定的供應商是否已設定 API Key
function hasApiKey() {
  const p = cachedSettings.provider;
  const k = cachedSettings.apiKeys && cachedSettings.apiKeys[p];
  return !!(k && k.trim());
}

// ---------- 設定：讀取並跟隨變更 ----------

chrome.storage.local.get('settings').then(({ settings }) => {
  cachedSettings = normalizeSettings(settings);
});

chrome.storage.onChanged.addListener((changes, area) => {
  if (area === 'local' && changes.settings) {
    cachedSettings = normalizeSettings(changes.settings.newValue);
  }
});

// ---------- 小工具 ----------

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

function el(tag, styles, text) {
  const node = document.createElement(tag);
  if (styles) node.style.cssText = styles;
  if (text != null) node.textContent = text;
  return node;
}

function hashId(s) {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) | 0;
  return (h >>> 0).toString(36);
}

function cleanText(s) {
  return (s || '').replace(/\s+/g, ' ').trim();
}

// ---------- Facebook 專用輔助（在地化關鍵字用「英文＋繁中」做子字串比對，不做等值比對） ----------

const FB_KW = {
  reply: ['reply', '回覆', '回复'],
  comment: ['comment', '留言', '評論', '评论'],
  message: ['message', 'send a message', '訊息', '傳送訊息', '輸入訊息'],
  createPost: ['create post', "what's on your mind", '建立貼文', '在想些什麼', '你在想什麼'],
};
function fbHasKw(s, list) {
  s = (s || '').toLowerCase();
  return list.some((k) => s.includes(k.toLowerCase()));
}
function fbIsChrome(s) {
  return (
    fbHasKw(s, ['like', 'reply', 'share', 'comment', '讚', '按讚', '回覆', '分享', '留言']) ||
    s.includes('•') ||
    /\bago\b/i.test(s) ||
    /(剛剛|小時|分鐘|天前|週前|年前|秒前)/.test(s) ||
    /^\d+\s*(min|hr|h|d|w|m|s|y)\b/i.test(s) ||
    /^\d+$/.test(s)
  );
}
// 作者：留言 article 內第一個「個人檔案連結」的文字（以 path 過濾，不看 query，
// 因為個人檔案連結的 query 常帶 comment_id）。退而求其次用 h3/h4/strong/b。
function fbAuthor(article) {
  const links = article.querySelectorAll('a[href*="facebook.com"], a[href^="/"]');
  for (const a of links) {
    const path = (a.getAttribute('href') || '').split('?')[0];
    if (/\/(comment|reply|photo|photos|hashtag|reactions?|ufi|posts|permalink|videos)\//.test(path)) continue;
    const name =
      cleanText(a.querySelector('span[dir="auto"]')?.textContent) ||
      cleanText(a.querySelector('span')?.textContent) ||
      cleanText(a.textContent);
    if (name && !fbIsChrome(name)) return name;
  }
  const h = article.querySelector('h3, h4, strong, b');
  const t = cleanText(h?.textContent);
  if (t && !fbIsChrome(t)) return t;
  return '';
}
// 內文：留言 article 內第一個合格的 dir="auto" 區塊（排除作者名、時間、UI 字樣）。
// 注意：不設長度下限（CJK 留言常很短，例如「百合男子」），改以關鍵字/時間戳過濾。
function fbText(article, author) {
  const blocks = article.querySelectorAll('div[dir="auto"]');
  for (const d of blocks) {
    const t = (d.innerText || '').trim();
    if (!t) continue;
    if (t === author) continue;
    if (/^\d+\s*(min|hr|h|d|w|m|s|y)\b/i.test(t)) continue;
    if (fbHasKw(t, ['replied', 'view replies', '已回覆', '查看回覆'])) continue;
    if (fbIsChrome(t)) continue;
    return t;
  }
  return '';
}

// ---------- 平台轉接器 ----------
// 每個平台提供：
//   replyBox(target)   由事件目標找出「留言回覆的編輯框」，非回覆框則回 null
//   targetComment(box) 由回覆框找出正在回覆的那一則留言 → { author, text } 或 null
//   composer(box)      要注入控制列的容器
//   context()          頁面層級脈絡 { title, owner }（可為空字串）
//   pageKey()          用於去重的頁面識別字串
//   fallbackFill(box,text)  execCommand 失敗時的後備填入（可省略）

const PLATFORMS = {
  youtube: {
    id: 'youtube',
    keepMention: true, // 保留 YouTube 巢狀回覆自動帶入的 @提及
    fallbackFill(box, text) {
      box.textContent = text;
      box.dispatchEvent(new InputEvent('input', { bubbles: true, data: text }));
    },
    replyBox(target) {
      return target.closest('#contenteditable-root');
    },
    targetComment(box) {
      const thread = box.closest('ytd-comment-thread-renderer');
      if (!thread) return null;
      const comments = [
        ...thread.querySelectorAll('ytd-comment-view-model, ytd-comment-renderer'),
      ];
      if (!comments.length) return null;
      let c = comments[0];
      for (const x of comments) {
        if (x.compareDocumentPosition(box) & Node.DOCUMENT_POSITION_FOLLOWING) c = x;
      }
      const author = cleanText(c.querySelector('#author-text')?.textContent);
      const text = (c.querySelector('#content-text')?.innerText || '').trim();
      if (!text) return null;
      return { author, text };
    },
    composer(box) {
      return box.closest('ytd-commentbox') || box.closest('#reply-dialog') || box.parentElement;
    },
    context() {
      const t = document.querySelector('ytd-watch-metadata h1 yt-formatted-string');
      const title = (t?.textContent || document.title.replace(/ - YouTube$/, '')).trim();
      const a = document.querySelector(
        'ytd-video-owner-renderer #channel-name a, #owner #channel-name a'
      );
      return { title, owner: cleanText(a?.textContent) };
    },
    pageKey() {
      return new URLSearchParams(location.search).get('v') || location.pathname;
    },
  },

  // Facebook 的 DOM 為混淆、常變動的自動 class，且 aria-label 會依語言在地化；以下以「結構/語意
  // 訊號」為主（aria-label 的回覆/留言字樣、contenteditable/role=textbox/data-lexical-editor、
  // role=article、dir=auto、個人檔案連結 path）。回覆框在版面上與留言 article 是「同層」而非
  // 巢狀，故不能用「框在 article 之內」來判斷（那會直接漏掉）。若 FB 改版，改這一區與上方 fb* 輔助。
  facebook: {
    id: 'facebook',
    keepMention: false, // 直接刪掉自動帶入的名字，只填回覆內容（回覆本身已會通知對方）
    // Lexical：execCommand 失敗時改用合成 paste（帶 DataTransfer）；嚴禁寫 textContent。
    fallbackFill(box, text) {
      try {
        const dt = new DataTransfer();
        dt.setData('text/plain', text);
        const ev = new ClipboardEvent('paste', { bubbles: true, cancelable: true });
        Object.defineProperty(ev, 'clipboardData', { value: dt });
        box.dispatchEvent(ev);
      } catch (_) {
        /* 放棄；切勿改 textContent（會破壞 Lexical 狀態） */
      }
    },
    replyBox(target) {
      const box =
        target.closest('div[contenteditable="true"][role="textbox"][data-lexical-editor="true"]') ||
        target.closest('div[contenteditable="true"][role="textbox"]');
      if (!box) return null;
      if (/\/messages(\/|$)/.test(location.pathname)) return null; // 排除 Messenger
      // 主判斷：aria-label / aria-placeholder 的語意（在地化）。回覆框文案如
      // 「以<名稱>的身分回覆 / 留言」「Reply/Comment as …」「Write a reply/comment…」。
      const al = `${box.getAttribute('aria-label') || ''} ${box.getAttribute('aria-placeholder') || ''}`;
      if (al.trim()) {
        if (fbHasKw(al, FB_KW.message) || fbHasKw(al, FB_KW.createPost)) return null;
        if (fbHasKw(al, FB_KW.reply) || fbHasKw(al, FB_KW.comment) || al.includes('身分')) return box;
      }
      // 沒有可判讀的 aria-label 時，退回結構判斷：位於留言 article 之內
      if (box.closest('[role="article"]')) return box;
      return null;
    },
    targetComment(box) {
      // 正在回覆的留言 = DOM 順序上「位於回覆框之前、離它最近」的 article。
      // （回覆框與留言同層或在貼文 article 之內；取最後一個 precede 者可同時涵蓋
      //  平鋪版面與「貼文 article 包住一切」的情況——留言 article 比貼文晚出現。）
      let article = null;
      for (const a of document.querySelectorAll('[role="article"]')) {
        if (a.compareDocumentPosition(box) & Node.DOCUMENT_POSITION_FOLLOWING) article = a;
      }
      if (!article) return null;
      const author = fbAuthor(article);
      const text = fbText(article, author);
      if (!text) return null;
      return { author, text };
    },
    composer(box) {
      return box.closest('form') || box.parentElement;
    },
    context() {
      // 盡力而為：最外層（role=article 巢狀最淺）者視為貼文，取其作者與內文當脈絡；
      // 取不到就留空（prompt 會以通用語句處理）。
      const articles = [...document.querySelectorAll('[role="article"]')];
      let best = null;
      let bestDepth = Infinity;
      for (const a of articles) {
        let d = 0;
        let p = a.parentElement;
        while (p) {
          if (p.matches && p.matches('[role="article"]')) d++;
          p = p.parentElement;
        }
        if (d < bestDepth) {
          bestDepth = d;
          best = a;
        }
      }
      const owner = best ? fbAuthor(best) : '';
      let title = (document.title || '').replace(/\s*[|\-–]\s*Facebook\s*$/i, '').trim();
      if (best) {
        const body = fbText(best, owner);
        if (body) title = body.slice(0, 120);
      }
      return { title, owner };
    },
    pageKey() {
      const u = new URL(location.href);
      const q = u.searchParams;
      return (
        q.get('story_fbid') ||
        q.get('fbid') ||
        (u.pathname.match(/\/(?:posts|permalink|reel|videos|photo)\/([\w.-]+)/) || [])[1] ||
        u.pathname
      );
    },
  },
};

function pickPlatform() {
  const h = location.hostname;
  if (/(^|\.)youtube\.com$/.test(h)) return PLATFORMS.youtube;
  if (/(^|\.)facebook\.com$/.test(h)) return PLATFORMS.facebook;
  return null;
}

const platform = pickPlatform();

function commentKey(c) {
  return hashId(`${platform.pageKey()}|${c.author}|${c.text.slice(0, 120)}`);
}

// ---------- 提及前綴 + 填入回覆框 ----------

// 拆出回覆框開頭「自動帶入的提及」與其後真正的內文，讓我們保留提及、把回覆接在後面。
//  - YouTube：提及是「@handle」形式。
//  - Facebook：回覆某則留言時自動帶入的提及是「留言作者名」本身（無 @，是 Lexical mention 節點），
//    所以用該留言的作者名比對開頭。
// JS 的 \s 與 String.trim() 本就涵蓋 nbsp（U+00A0）。
function splitMention(box, comment) {
  const raw = box.textContent || '';
  const m = raw.match(/^\s*((?:@\S+\s*)+)/);
  if (m) return { mention: m[1].trim(), body: raw.slice(m[0].length).trim() };

  const author = comment && comment.author ? comment.author.replace(/ /g, ' ').trim() : '';
  if (author) {
    const t = raw.replace(/ /g, ' ');
    if (t.replace(/^\s+/, '').startsWith(author)) {
      const idx = t.indexOf(author) + author.length;
      return { mention: author, body: t.slice(idx).trim() };
    }
  }
  return { mention: '', body: raw.trim() };
}

async function fillBox(box, text, comment) {
  box.focus();
  await sleep(50);

  // YouTube：保留自動帶入的 @提及，把回覆接在其後。
  // Facebook（keepMention:false）：直接刪掉自動帶入的名字，只填回覆內容——
  //   提及是 Lexical 節點、重填後只會變成純文字，而回覆本身已會通知對方。
  const { mention } = splitMention(box, comment);
  const finalText = mention && platform.keepMention ? `${mention} ${text}` : text;

  // 全選 → 刪除既有內容 → 重新插入。execCommand 會觸發原生 beforeinput/input 事件，
  // YouTube 與 Facebook（Lexical）皆透過此路徑更新狀態並啟用送出鈕。
  const sel = window.getSelection();
  const range = document.createRange();
  range.selectNodeContents(box);
  sel.removeAllRanges();
  sel.addRange(range);
  document.execCommand('delete');

  const inserted = document.execCommand('insertText', false, finalText);
  if (!inserted || !(box.textContent || '').trim()) {
    if (platform.fallbackFill) platform.fallbackFill(box, finalText);
  }
}

// ---------- 控制列（含產生按鈕與狀態） ----------

function setStatus(status, text, kind) {
  if (!status) return;
  status.textContent = text || '';
  status.style.color = kind === 'err' ? '#f28b82' : kind === 'ok' ? '#81c995' : '#aaa';
}

function ensureControlBar(box) {
  const composer = platform.composer(box);
  if (!composer) return null;

  let bar = composer.querySelector(':scope > .cb-bar');
  if (bar) return bar;

  bar = el(
    'div',
    'display:flex;align-items:center;gap:10px;margin:8px 0 4px;flex-wrap:wrap;' +
      'font:12px/1.4 Roboto,system-ui,-apple-system,"Microsoft JhengHei",sans-serif'
  );
  bar.className = 'cb-bar';

  const btn = el(
    'button',
    'display:inline-flex;align-items:center;gap:4px;padding:6px 12px;border-radius:18px;' +
      'border:none;cursor:pointer;font:600 12px Roboto,system-ui,sans-serif;' +
      'background:#3ea6ff;color:#0f0f0f',
    BTN_LABEL
  );
  btn.type = 'button';

  const status = el('span', 'font:12px Roboto,system-ui;color:#aaa');
  status.className = 'cb-status';

  btn.addEventListener('click', (e) => {
    e.preventDefault();
    e.stopPropagation();
    generate(box, btn, status, false);
  });

  bar.appendChild(btn);
  bar.appendChild(status);

  const footer = composer.querySelector('#footer');
  if (footer && footer.parentElement === composer) composer.insertBefore(bar, footer);
  else composer.appendChild(bar);

  return bar;
}

// ---------- 產生回覆 ----------

async function generate(box, btn, status, isAuto) {
  if (generating) return;

  const comment = platform.targetComment(box);
  if (!comment) {
    if (!isAuto) setStatus(status, '找不到對應的留言', 'err');
    return;
  }
  if (!comment.text) {
    if (!isAuto) setStatus(status, '讀不到留言內容', 'err');
    return;
  }
  if (!hasApiKey()) {
    if (!isAuto) setStatus(status, '尚未設定 API Key，請點工具列的擴充功能圖示設定', 'err');
    return;
  }

  generating = true;
  btn.disabled = true;
  const label = btn.textContent;
  btn.textContent = '產生中…';
  setStatus(status, '', '');

  try {
    const ctx = platform.context();
    const resp = await chrome.runtime.sendMessage({
      type: 'GENERATE_REPLY',
      payload: {
        platform: platform.id,
        author: comment.author,
        text: comment.text.slice(0, 1500),
        title: ctx.title,
        owner: ctx.owner,
      },
    });
    if (!resp?.ok) throw new Error(resp?.error || '背景服務無回應');

    await fillBox(box, resp.reply.trim(), comment);
    autoGenerated.add(commentKey(comment));
    btn.textContent = '🔄 重新產生';
    setStatus(status, '已填入草稿，確認後請自行送出', 'ok');
  } catch (e) {
    btn.textContent = label;
    setStatus(status, e.message, 'err');
  } finally {
    generating = false;
    btn.disabled = false;
  }
}

// ---------- 監聽回覆框取得焦點 ----------

if (platform) {
  document.addEventListener(
    'focusin',
    (e) => {
      const target = e.target;
      if (!(target instanceof Element)) return;
      const box = platform.replyBox(target);
      if (!box) return;

      // SPA 換頁：網址變了就清空自動產生記錄
      if (location.href !== lastHref) {
        lastHref = location.href;
        autoGenerated.clear();
      }

      const comment = platform.targetComment(box);
      if (!comment) return; // 不是「回覆某則留言」的框，略過

      const bar = ensureControlBar(box);
      if (!bar) return;
      const btn = bar.querySelector('button');
      const status = bar.querySelector('.cb-status');

      // 產生中觸發的 focusin（例如 fillBox 內部的 box.focus()）：不動 UI、不排程，避免重入
      if (generating) return;

      const body = splitMention(box, comment).body;

      // 對「空的」回覆框重置控制列外觀（把自動帶入的提及視為空）
      if (!body) {
        btn.textContent = BTN_LABEL;
        btn.disabled = false;
        setStatus(status, '', '');
      }

      if (!cachedSettings.autoOnFocus) return;

      const composer = platform.composer(box);
      if (!composer) return;

      // 僅在框沒有「真正的內文」（只有空白或自動帶入的提及）、且該留言尚未自動產生過時觸發。
      const cid = commentKey(comment);
      if (autoGenerated.has(cid)) return;
      if (body) return; // 使用者已自行輸入內文 → 不自動覆蓋
      if (composer.dataset.cbAutoComment === cid) return;

      composer.dataset.cbAutoComment = cid;
      // 稍等版面穩定再產生；此時若使用者已開始打字（框有真正內文），則放棄自動產生
      setTimeout(() => {
        if (!generating && !splitMention(box, comment).body && !autoGenerated.has(cid)) {
          generate(box, btn, status, true);
        }
      }, 250);
    },
    true
  );
}
