// CommentBot — content script（支援 YouTube 與 Facebook）
// 依「回覆模式」處理留言回覆，只用選定的 AI 針對「單一」留言產生回覆並填入回覆框：
//   hidden   手動 —— 只在使用者按「✨ AI 產生回覆」時才產生，永不自動送出
//   checking 檢查 —— 聚焦回覆框時自動產生草稿並填入，但不送出（預設）
//   lazy     懶人 —— 聚焦回覆框時自動產生並「自動送出」
//   crazy    瘋狂 —— 自動掃描頁面留言，逐一開啟回覆框、產生並「自動送出」
// 平台差異（選擇器、擷取留言、填入與送出方式）集中在 PLATFORMS，其餘邏輯共用。

'use strict';

const BTN_LABEL = '✨ AI 產生回覆';
const CRAZY_DELAY = 4000; // crazy 模式每則之間的間隔（毫秒），避免瞬間大量送出
const CRAZY_MAX_TRIES = 2; // crazy 模式同一則留言的最多重試次數

let cachedSettings = normalizeSettings(null);
let generating = false;
const autoGenerated = new Set(); // 本頁工作階段中已產生過回覆的留言 key（去重）
let lastHref = location.href;

// crazy 模式狀態
let crazyRunning = false;
let crazyTimer = null;

// 目前選定的供應商是否已設定 API Key
function hasApiKey() {
  const p = cachedSettings.provider;
  const k = cachedSettings.apiKeys && cachedSettings.apiKeys[p];
  return !!(k && k.trim());
}

// 留言篩選：留言內容是否符合設定的篩選條件（不符合則任何模式都不回覆）。
// 未設定篩選（僅空白）→ 全部通過；無效的 regex → 一律不通過（fail-closed，
// 避免因篩選失效而在自動送出模式下大量回覆；popup 會即時提示 regex 錯誤）。
// 只在「判斷是否有設定」時 trim，實際比對用原字串（保留使用者刻意留的頭尾空白）。
let filterRe = null; // 已編譯的篩選 regex 快取（避免每則留言重編譯）
let filterReKey = '';
function passesFilter(text) {
  const pat = cachedSettings.filterPattern || '';
  if (!pat.trim()) return true;
  // 限制比對長度（與送給 AI 的 1500 字一致），降低失控 regex 卡死主執行緒的風險
  const t = (text || '').slice(0, 1500);
  if (cachedSettings.filterRegex) {
    const key = (cachedSettings.filterIgnoreCase ? 'i|' : '|') + pat;
    if (key !== filterReKey) {
      filterReKey = key;
      try {
        filterRe = new RegExp(pat, cachedSettings.filterIgnoreCase ? 'i' : '');
      } catch (_) {
        filterRe = null; // 無效 regex
      }
    }
    return filterRe ? filterRe.test(t) : false; // 無效 → fail-closed（不回覆）
  }
  return cachedSettings.filterIgnoreCase
    ? t.toLowerCase().includes(pat.toLowerCase())
    : t.includes(pat);
}

// ---------- 設定：讀取並跟隨變更 ----------

chrome.storage.local.get('settings').then(({ settings }) => {
  cachedSettings = normalizeSettings(settings);
  scheduleCrazy();
});

chrome.storage.onChanged.addListener((changes, area) => {
  if (area === 'local' && changes.settings) {
    cachedSettings = normalizeSettings(changes.settings.newValue);
    // 篩選條件可能變了 → 清除「暫時性」的篩選略過標記，讓下次掃描重新評估
    // （已回覆／重試耗盡的 cbCrazy 才是永久性，不清）。
    document.querySelectorAll('[data-cb-filtered]').forEach((b) => delete b.dataset.cbFiltered);
    scheduleCrazy();
  }
});

// ---------- 小工具 ----------

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

function el(tag, styles, text) {
  const node = document.createElement(tag);
  if (styles) node.style.cssText = styles;
  if (text != null) node.textContent = text;
  return node;
}

function hashId(s) {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) | 0;
  return (h >>> 0).toString(36);
}

function cleanText(s) {
  return (s || '').replace(/\s+/g, ' ').trim();
}

const isVisible = (elm) => !!(elm && elm.offsetParent !== null);

// ---------- Facebook 專用輔助（在地化關鍵字用「英文＋繁中」做子字串比對，不做等值比對） ----------

const FB_KW = {
  reply: ['reply', '回覆', '回复'],
  comment: ['comment', '留言', '評論', '评论'],
  message: ['message', 'send a message', '訊息', '傳送訊息', '輸入訊息'],
  createPost: ['create post', "what's on your mind", '建立貼文', '在想些什麼', '你在想什麼'],
};
// 送出鈕：以「錨定開頭」比對（避免子字串誤判），再排除各種媒體挑選器。
const FB_SUBMIT_RE = /^(comment|reply|post|submit|發佈|發布|送出|傳送|貼文留言)/i;
const FB_PICKER_RE =
  /(sticker|gif|avatar|emoji|photo|video|attach|with a |with an |貼圖|表情|相片|影片|大頭貼|虛擬替身|回應|聲音)/i;

function fbHasKw(s, list) {
  s = (s || '').toLowerCase();
  return list.some((k) => s.includes(k.toLowerCase()));
}
function fbIsChrome(s) {
  return (
    fbHasKw(s, ['like', 'reply', 'share', 'comment', '讚', '按讚', '回覆', '分享', '留言']) ||
    s.includes('•') ||
    /\bago\b/i.test(s) ||
    /(剛剛|小時|分鐘|天前|週前|年前|秒前)/.test(s) ||
    /^\d+\s*(min|hr|h|d|w|m|s|y)\b/i.test(s) ||
    /^\d+$/.test(s)
  );
}
// 作者：留言 article 內第一個「個人檔案連結」的文字（以 path 過濾，不看 query，
// 因為個人檔案連結的 query 常帶 comment_id）。退而求其次用 h3/h4/strong/b。
function fbAuthor(article) {
  const links = article.querySelectorAll('a[href*="facebook.com"], a[href^="/"]');
  for (const a of links) {
    const path = (a.getAttribute('href') || '').split('?')[0];
    if (/\/(comment|reply|photo|photos|hashtag|reactions?|ufi|posts|permalink|videos)\//.test(path)) continue;
    const name =
      cleanText(a.querySelector('span[dir="auto"]')?.textContent) ||
      cleanText(a.querySelector('span')?.textContent) ||
      cleanText(a.textContent);
    if (name && !fbIsChrome(name)) return name;
  }
  const h = article.querySelector('h3, h4, strong, b');
  const t = cleanText(h?.textContent);
  if (t && !fbIsChrome(t)) return t;
  return '';
}
// 內文：留言 article 內第一個合格的 dir="auto" 區塊（排除作者名、時間、UI 字樣）。
// 注意：不設長度下限（CJK 留言常很短，例如「百合男子」），改以關鍵字/時間戳過濾。
function fbText(article, author) {
  const blocks = article.querySelectorAll('div[dir="auto"]');
  for (const d of blocks) {
    const t = (d.innerText || '').trim();
    if (!t) continue;
    if (t === author) continue;
    if (/^\d+\s*(min|hr|h|d|w|m|s|y)\b/i.test(t)) continue;
    if (fbHasKw(t, ['replied', 'view replies', '已回覆', '查看回覆'])) continue;
    if (fbIsChrome(t)) continue;
    return t;
  }
  return '';
}

// ---------- 平台轉接器 ----------
// 每個平台提供：
//   replyBox(target)   由事件目標找出「留言回覆的編輯框」，非回覆框則回 null
//   targetComment(box) 由回覆框找出正在回覆的那一則留言 → { author, text } 或 null
//   composer(box)      要注入控制列的容器
//   context()          頁面層級脈絡 { title, owner }（可為空字串）
//   pageKey()          用於去重的頁面識別字串
//   keepMention        填入時是否保留自動帶入的提及（YouTube:true / Facebook:false）
//   fallbackFill(box,text)  execCommand 失敗時的後備填入
//   submit(box)        自動送出回覆（lazy / crazy 用）→ Promise<boolean>（true=確認已送出）
//   boxSelector        頁面上所有回覆框的選擇器（crazy：找剛開啟的框）
//   replyButtons()     頁面上所有留言的「回覆」開關按鈕（crazy：逐一開啟）

const PLATFORMS = {
  youtube: {
    id: 'youtube',
    keepMention: true, // 保留 YouTube 巢狀回覆自動帶入的 @提及
    boxSelector: '#contenteditable-root',
    fallbackFill(box, text) {
      box.textContent = text;
      box.dispatchEvent(new InputEvent('input', { bubbles: true, data: text }));
    },
    replyBox(target) {
      return target.closest('#contenteditable-root');
    },
    targetComment(box) {
      const thread = box.closest('ytd-comment-thread-renderer');
      if (!thread) return null;
      const comments = [
        ...thread.querySelectorAll('ytd-comment-view-model, ytd-comment-renderer'),
      ];
      if (!comments.length) return null;
      let c = comments[0];
      for (const x of comments) {
        if (x.compareDocumentPosition(box) & Node.DOCUMENT_POSITION_FOLLOWING) c = x;
      }
      const author = cleanText(c.querySelector('#author-text')?.textContent);
      const text = (c.querySelector('#content-text')?.innerText || '').trim();
      if (!text) return null;
      return { author, text };
    },
    composer(box) {
      return box.closest('ytd-commentbox') || box.closest('#reply-dialog') || box.parentElement;
    },
    context() {
      const t = document.querySelector('ytd-watch-metadata h1 yt-formatted-string');
      const title = (t?.textContent || document.title.replace(/ - YouTube$/, '')).trim();
      const a = document.querySelector(
        'ytd-video-owner-renderer #channel-name a, #owner #channel-name a'
      );
      return { title, owner: cleanText(a?.textContent) };
    },
    pageKey() {
      return new URLSearchParams(location.search).get('v') || location.pathname;
    },
    async submit(box) {
      const cb = box.closest('ytd-commentbox');
      if (!cb) return false;
      await sleep(200); // 等 input 事件讓送出鈕啟用
      const btn = cb.querySelector('#submit-button button, #submit-button [role="button"]');
      if (!btn) return false;
      let disabled = true;
      for (let i = 0; i < 12; i++) {
        disabled = btn.disabled || btn.getAttribute('aria-disabled') === 'true';
        if (!disabled) break;
        await sleep(120);
      }
      if (disabled) return false; // 仍停用：點擊為 no-op，回報送出失敗而非假成功
      btn.click();
      return true;
    },
    replyButtons() {
      return [
        ...document.querySelectorAll(
          'ytd-comment-thread-renderer #reply-button-end button, ytd-comment-thread-renderer #reply-button-end [role="button"]'
        ),
      ];
    },
  },

  // Facebook 的 DOM 為混淆、常變動的自動 class，且 aria-label 會依語言在地化；以下以「結構/語意
  // 訊號」為主。回覆框在版面上與留言 article 是「同層」而非巢狀，故不能用「框在 article 之內」
  // 判斷。若 FB 改版，改這一區與上方 fb* 輔助。
  facebook: {
    id: 'facebook',
    keepMention: false, // 直接刪掉自動帶入的名字，只填回覆內容（回覆本身已會通知對方）
    boxSelector:
      'div[contenteditable="true"][role="textbox"][data-lexical-editor="true"], div[contenteditable="true"][role="textbox"]',
    // Lexical：execCommand 失敗時改用合成 paste（帶 DataTransfer）；嚴禁寫 textContent。
    fallbackFill(box, text) {
      try {
        const dt = new DataTransfer();
        dt.setData('text/plain', text);
        const ev = new ClipboardEvent('paste', { bubbles: true, cancelable: true });
        Object.defineProperty(ev, 'clipboardData', { value: dt });
        box.dispatchEvent(ev);
      } catch (_) {
        /* 放棄；切勿改 textContent（會破壞 Lexical 狀態） */
      }
    },
    replyBox(target) {
      const box =
        target.closest('div[contenteditable="true"][role="textbox"][data-lexical-editor="true"]') ||
        target.closest('div[contenteditable="true"][role="textbox"]');
      if (!box) return null;
      if (/\/messages(\/|$)/.test(location.pathname)) return null; // 排除 Messenger
      const al = `${box.getAttribute('aria-label') || ''} ${box.getAttribute('aria-placeholder') || ''}`;
      if (al.trim()) {
        if (fbHasKw(al, FB_KW.message) || fbHasKw(al, FB_KW.createPost)) return null;
        if (fbHasKw(al, FB_KW.reply) || fbHasKw(al, FB_KW.comment) || al.includes('身分')) return box;
        return null; // 有 aria-label 但不像回覆/留言框 → 拒絕
      }
      if (box.closest('[role="article"]')) return box;
      return null;
    },
    targetComment(box) {
      // 正在回覆的留言 = DOM 順序上「位於回覆框之前、離它最近」的 article
      let article = null;
      for (const a of document.querySelectorAll('[role="article"]')) {
        if (a.compareDocumentPosition(box) & Node.DOCUMENT_POSITION_FOLLOWING) article = a;
      }
      if (!article) return null;
      const author = fbAuthor(article);
      const text = fbText(article, author);
      if (!text) return null;
      return { author, text };
    },
    composer(box) {
      return box.closest('form') || box.parentElement;
    },
    context() {
      const articles = [...document.querySelectorAll('[role="article"]')];
      let best = null;
      let bestDepth = Infinity;
      for (const a of articles) {
        let d = 0;
        let p = a.parentElement;
        while (p) {
          if (p.matches && p.matches('[role="article"]')) d++;
          p = p.parentElement;
        }
        if (d < bestDepth) {
          bestDepth = d;
          best = a;
        }
      }
      const owner = best ? fbAuthor(best) : '';
      let title = (document.title || '').replace(/\s*[|\-–]\s*Facebook\s*$/i, '').trim();
      if (best) {
        const body = fbText(best, owner);
        if (body) title = body.slice(0, 120);
      }
      return { title, owner };
    },
    pageKey() {
      const u = new URL(location.href);
      const q = u.searchParams;
      return (
        q.get('story_fbid') ||
        q.get('fbid') ||
        (u.pathname.match(/\/(?:posts|permalink|reel|videos|photo)\/([\w.-]+)/) || [])[1] ||
        u.pathname
      );
    },
    async submit(box) {
      await sleep(200);
      // 搜尋範圍：優先 form；FB composer 未必被 <form> 包住，故往上找含送出鈕語意節點的祖先
      let scope = box.closest('form');
      if (!scope) {
        scope = box;
        for (let i = 0; i < 6 && scope.parentElement; i++) {
          scope = scope.parentElement;
          if (scope.querySelector('#focused-state-composer-submit')) break;
        }
      }

      // 1) 送出鈕：優先語意 id，再用「錨定開頭且非挑選器」的 aria-label
      let btn = null;
      const idBtn = scope.querySelector('#focused-state-composer-submit [role="button"]');
      if (idBtn && isVisible(idBtn)) btn = idBtn;
      if (!btn) {
        for (const b of scope.querySelectorAll('[role="button"][aria-label]')) {
          if (!isVisible(b)) continue;
          const al = (b.getAttribute('aria-label') || '').trim();
          if (FB_SUBMIT_RE.test(al) && !FB_PICKER_RE.test(al)) {
            btn = b;
            break;
          }
        }
      }

      if (btn) {
        btn.click();
      } else {
        // 2) 後備：對編輯框送 Enter（Lexical 單行 composer 以 Enter 送出）
        box.focus();
        const opt = { key: 'Enter', code: 'Enter', keyCode: 13, which: 13, bubbles: true, cancelable: true };
        box.dispatchEvent(new KeyboardEvent('keydown', opt));
        box.dispatchEvent(new KeyboardEvent('keypress', opt));
        box.dispatchEvent(new KeyboardEvent('keyup', opt));
      }

      // 驗證：成功送出後 Lexical 會清空或移除編輯框；於逾時內確認才算成功
      for (let i = 0; i < 20; i++) {
        await sleep(150);
        if (!box.isConnected || !cleanText(box.textContent)) return true;
      }
      return false;
    },
    replyButtons() {
      const out = [];
      for (const b of document.querySelectorAll('[role="button"], [role="link"]')) {
        const t = cleanText(b.textContent);
        // 精準比對「回覆 / Reply」（避免抓到「查看 N 則回覆」等）
        if (/^(回覆|回复|reply)$/i.test(t)) out.push(b);
      }
      return out;
    },
  },
};

function pickPlatform() {
  const h = location.hostname;
  if (/(^|\.)youtube\.com$/.test(h)) return PLATFORMS.youtube;
  if (/(^|\.)facebook\.com$/.test(h)) return PLATFORMS.facebook;
  return null;
}

const platform = pickPlatform();

function commentKey(c) {
  return hashId(`${platform.pageKey()}|${c.author}|${c.text.slice(0, 120)}`);
}

// ---------- 提及前綴 + 填入回覆框 ----------

// 拆出回覆框開頭「自動帶入的提及」與其後真正的內文。
//  - YouTube：提及是「@handle」形式。
//  - Facebook：回覆某則留言時自動帶入的提及是「留言作者名」本身（無 @，是 Lexical mention 節點）。
// 需把 nbsp（U+00A0）正規化為一般空白，startsWith 比對才不會因 nbsp 差異而失敗。
function splitMention(box, comment) {
  const raw = (box.textContent || '').replace(/ /g, ' ');
  const m = raw.match(/^\s*((?:@\S+\s*)+)/);
  if (m) return { mention: m[1].trim(), body: raw.slice(m[0].length).trim() };

  const author = comment && comment.author ? comment.author.replace(/ /g, ' ').trim() : '';
  if (author && raw.replace(/^\s+/, '').startsWith(author)) {
    const idx = raw.indexOf(author) + author.length;
    return { mention: author, body: raw.slice(idx).trim() };
  }
  return { mention: '', body: raw.trim() };
}

async function fillBox(box, text, comment) {
  box.focus();
  await sleep(50);

  // YouTube：保留自動帶入的 @提及，把回覆接在其後。
  // Facebook（keepMention:false）：直接刪掉自動帶入的名字，只填回覆內容——
  //   提及是 Lexical 節點、重填後只會變成純文字，而回覆本身已會通知對方。
  const { mention } = splitMention(box, comment);
  const finalText = mention && platform.keepMention ? `${mention} ${text}` : text;

  // 全選 → 刪除既有內容 → 重新插入。execCommand 會觸發原生 beforeinput/input 事件，
  // YouTube 與 Facebook（Lexical）皆透過此路徑更新狀態並啟用送出鈕。
  const sel = window.getSelection();
  const range = document.createRange();
  range.selectNodeContents(box);
  sel.removeAllRanges();
  sel.addRange(range);
  document.execCommand('delete');

  const inserted = document.execCommand('insertText', false, finalText);
  if (!inserted || !(box.textContent || '').trim()) {
    if (platform.fallbackFill) platform.fallbackFill(box, finalText);
  }
}

// ---------- 控制列（含產生按鈕與狀態） ----------

function setStatus(status, text, kind) {
  if (!status) return;
  status.textContent = text || '';
  status.style.color = kind === 'err' ? '#f28b82' : kind === 'ok' ? '#81c995' : '#aaa';
}

function ensureControlBar(box) {
  const composer = platform.composer(box);
  if (!composer) return null;

  let bar = composer.querySelector(':scope > .cb-bar');
  if (bar) return bar;

  bar = el(
    'div',
    'display:flex;align-items:center;gap:10px;margin:8px 0 4px;flex-wrap:wrap;' +
      'font:12px/1.4 Roboto,system-ui,-apple-system,"Microsoft JhengHei",sans-serif'
  );
  bar.className = 'cb-bar';

  const btn = el(
    'button',
    'display:inline-flex;align-items:center;gap:4px;padding:6px 12px;border-radius:18px;' +
      'border:none;cursor:pointer;font:600 12px Roboto,system-ui,sans-serif;' +
      'background:#3ea6ff;color:#0f0f0f',
    BTN_LABEL
  );
  btn.type = 'button';

  const status = el('span', 'font:12px Roboto,system-ui;color:#aaa');
  status.className = 'cb-status';

  // 手動按鈕永遠只產生草稿、不自動送出（自動送出僅由 lazy / crazy 的自動流程負責）
  btn.addEventListener('click', (e) => {
    e.preventDefault();
    e.stopPropagation();
    generate(box, btn, status, { auto: false, submit: false });
  });

  bar.appendChild(btn);
  bar.appendChild(status);

  const footer = composer.querySelector('#footer');
  if (footer && footer.parentElement === composer) composer.insertBefore(bar, footer);
  else composer.appendChild(bar);

  return bar;
}

// ---------- 產生回覆（可選自動送出） ----------
// 回傳值：true 代表「已成功填入草稿」（不論送出成敗）；false 代表在填入前就中止/失敗
// （鎖忙碌、讀不到留言、無金鑰、框內已有內文、或網路/API 錯誤）。crazy 佇列據此決定是否重試。

async function generate(box, btn, status, opts = {}) {
  const { auto = false, submit = false } = opts;
  if (generating) return false;

  const comment = platform.targetComment(box);
  if (!comment || !comment.text) {
    if (!auto) setStatus(status, comment ? '讀不到留言內容' : '找不到對應的留言', 'err');
    return false;
  }
  // 留言篩選：不符合條件的留言，任何模式都不回覆
  if (!passesFilter(comment.text)) {
    if (!auto) setStatus(status, '留言不符合篩選條件，略過', '');
    return false;
  }
  if (!hasApiKey()) {
    if (!auto) setStatus(status, '尚未設定 API Key，請點工具列的擴充功能圖示設定', 'err');
    return false;
  }
  // 自動流程：框內若已有真正內文，絕不覆蓋（保護使用者輸入 / 已存在的草稿）
  if (auto && splitMention(box, comment).body) return false;

  generating = true;
  const label = btn ? btn.textContent : '';
  if (btn) {
    btn.disabled = true;
    btn.textContent = '產生中…';
  }
  setStatus(status, '', '');

  let handled = false;
  try {
    const ctx = platform.context();
    const resp = await chrome.runtime.sendMessage({
      type: 'GENERATE_REPLY',
      payload: {
        platform: platform.id,
        author: comment.author,
        text: comment.text.slice(0, 1500),
        title: ctx.title,
        owner: ctx.owner,
      },
    });
    if (!resp?.ok) throw new Error(resp?.error || '背景服務無回應');

    await fillBox(box, resp.reply.trim(), comment);
    autoGenerated.add(commentKey(comment));
    handled = true;

    // 送出前重新確認模式：自動流程若使用者已切離 lazy/crazy，就只留草稿不送出
    const stillAuto = !auto || cachedSettings.mode === 'lazy' || cachedSettings.mode === 'crazy';
    if (submit && stillAuto && platform.submit) {
      setStatus(status, '送出中…', '');
      let ok = false;
      try {
        ok = await platform.submit(box);
      } catch (_) {
        ok = false;
      }
      if (btn) btn.textContent = ok ? '✅ 已送出' : BTN_LABEL;
      setStatus(status, ok ? '已自動送出' : '已填入草稿，但自動送出失敗，請手動送出', ok ? 'ok' : 'err');
    } else if (submit && !stillAuto) {
      if (btn) btn.textContent = '🔄 重新產生';
      setStatus(status, '已填入草稿（模式已變更，未自動送出）', 'ok');
    } else {
      if (btn) btn.textContent = '🔄 重新產生';
      setStatus(status, '已填入草稿，確認後請自行送出', 'ok');
    }
  } catch (e) {
    if (btn) btn.textContent = label || BTN_LABEL;
    setStatus(status, e.message, 'err');
  } finally {
    generating = false;
    if (btn) btn.disabled = false;
  }
  return handled;
}

// ---------- crazy 模式：自動掃描留言並逐一回覆送出 ----------

function scheduleCrazy() {
  if (!platform) return;
  if (cachedSettings.mode !== 'crazy') return;
  if (crazyTimer || crazyRunning) return;
  crazyTimer = setTimeout(() => {
    crazyTimer = null;
    runCrazyQueue();
  }, 1500);
}

// 等待「本次點擊後新出現、可見、屬於回覆框、且尚無內容」的框，避免蓋到別的框或使用者輸入。
async function waitForNewBox(before) {
  for (let i = 0; i < 25; i++) {
    await sleep(150);
    for (const b of document.querySelectorAll(platform.boxSelector)) {
      if (before.has(b)) continue; // 必須是點擊後才出現的新框
      if (!isVisible(b)) continue;
      if (!platform.replyBox(b)) continue; // 套用與 focusin 相同的排除（發文框 / Messenger）
      const c = platform.targetComment(b);
      if (!c || autoGenerated.has(commentKey(c))) continue;
      if (splitMention(b, c).body) continue; // 已有內容 → 不覆蓋
      return { box: b, comment: c };
    }
  }
  return null;
}

async function runCrazyQueue() {
  if (cachedSettings.mode !== 'crazy' || crazyRunning) return;
  if (!hasApiKey() || !platform.replyButtons) return;
  crazyRunning = true;
  try {
    for (const btn of platform.replyButtons()) {
      if (cachedSettings.mode !== 'crazy') break; // 中途改模式就停
      if (btn.dataset.cbCrazy) continue; // 已成功處理／重試耗盡（永久略過）
      if (btn.dataset.cbFiltered) continue; // 本次篩選不符（settings 變更時會清除以重評）
      if (!isVisible(btn)) continue; // 尚未顯示（虛擬捲動）→ 下次掃描再處理
      // 篩選預檢：由回覆鈕直接推得所屬留言，不符合就標記「篩選略過」、連框都不開。
      // 用 cbFiltered（可回復）而非 cbCrazy（永久），這樣之後放寬/修正篩選能重新納入。
      const pre = platform.targetComment(btn);
      if (pre && !passesFilter(pre.text)) {
        btn.dataset.cbFiltered = '1';
        continue;
      }
      const tries = Number(btn.dataset.cbCrazyTries || 0);
      if (tries >= CRAZY_MAX_TRIES) {
        btn.dataset.cbCrazy = '1'; // 試過上限仍失敗 → 放棄，不再重試
        continue;
      }

      const before = new Set(document.querySelectorAll(platform.boxSelector));
      btn.click(); // 開啟該留言的回覆框
      const found = await waitForNewBox(before);
      if (cachedSettings.mode !== 'crazy') break; // 開框期間切離 crazy → 停
      if (!found) {
        btn.dataset.cbCrazyTries = String(tries + 1);
        continue;
      }
      // box 端補捉：預檢用回覆鈕推得的留言若與實際框內留言不一致（FB 邊角情況），
      // 這裡用實際留言再判一次篩選；不符合就標記篩選略過（不重試、不產生）。
      if (!passesFilter(found.comment.text)) {
        btn.dataset.cbFiltered = '1';
        continue;
      }

      const bar = ensureControlBar(found.box);
      const b = bar && bar.querySelector('button');
      const s = bar && bar.querySelector('.cb-status');
      const ok = await generate(found.box, b, s, { auto: true, submit: true });
      if (ok) btn.dataset.cbCrazy = '1'; // 已填入 → 完成（送出成敗於狀態列顯示，不重複點擊）
      else btn.dataset.cbCrazyTries = String(tries + 1); // 填入前就失敗 → 保留重試
      await sleep(CRAZY_DELAY); // 節流，避免瞬間大量送出
    }
  } finally {
    crazyRunning = false;
  }
}

// ---------- 監聽回覆框取得焦點（hidden / checking / lazy） ----------

if (platform) {
  document.addEventListener(
    'focusin',
    (e) => {
      const target = e.target;
      if (!(target instanceof Element)) return;
      const box = platform.replyBox(target);
      if (!box) return;

      // SPA 換頁：網址變了就清空自動產生記錄
      if (location.href !== lastHref) {
        lastHref = location.href;
        autoGenerated.clear();
      }

      const comment = platform.targetComment(box);
      if (!comment) return; // 不是「回覆某則留言」的框，略過

      const bar = ensureControlBar(box);
      if (!bar) return;
      const btn = bar.querySelector('button');
      const status = bar.querySelector('.cb-status');

      // 產生中觸發的 focusin（例如 fillBox 內部的 box.focus()）：不動 UI、不排程，避免重入
      if (generating) return;

      const body = splitMention(box, comment).body;

      // 對「空的」回覆框重置控制列外觀（把自動帶入的提及視為空）
      if (!body) {
        btn.textContent = BTN_LABEL;
        btn.disabled = false;
        setStatus(status, '', '');
      }

      // hidden：只提供手動按鈕；crazy：由掃描佇列負責，這裡不介入
      const mode = cachedSettings.mode;
      if (mode !== 'checking' && mode !== 'lazy') return;

      const cid = commentKey(comment);
      if (autoGenerated.has(cid)) return;
      if (body) return; // 使用者已自行輸入內文 → 不自動覆蓋

      // 以「每框一個排程旗標」避免重複排程；此旗標會在實際執行或放棄時清除（不像舊版永不清除）。
      if (box.dataset.cbAutoPending === cid) return;
      box.dataset.cbAutoPending = cid;

      const submit = mode === 'lazy';
      const clearPending = () => {
        if (box.dataset.cbAutoPending === cid) delete box.dataset.cbAutoPending;
      };
      // 稍等版面穩定再產生；若鎖忙碌（另一則正在產生）則稍後重試，不直接丟棄。
      const tryAuto = () => {
        if (
          autoGenerated.has(cid) ||
          splitMention(box, comment).body || // 使用者已開始打字
          cachedSettings.mode !== mode // 模式已變更 → 交給後續 focusin 處理
        ) {
          clearPending();
          return;
        }
        if (generating) {
          setTimeout(tryAuto, 300);
          return;
        }
        clearPending();
        generate(box, btn, status, { auto: true, submit });
      };
      setTimeout(tryAuto, 250);
    },
    true
  );

  // crazy 模式：監聽新留言載入（無限捲動），並在初次載入時嘗試啟動
  const mo = new MutationObserver(() => scheduleCrazy());
  mo.observe(document.documentElement, { childList: true, subtree: true });
  scheduleCrazy();
}
